#**Dummy Variable method**

**Import Dependencies**

In [ ]:
import pandas as pd
import numpy as np

**Import Dataset**

In [ ]:
df= pd.read_csv('https://github.com/codebasics/py/raw/801ee0ee4d342fd22b89915dc0c4864250a0ec10/ML/5_one_hot_encoding/homeprices.csv#L4')
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [ ]:
dummies= pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [ ]:
merged= pd.concat([df, dummies], axis=1)
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [ ]:
# Drop original column now as well as one column of dummy, so avoid dummy trap

final= merged.drop(['town','west windsor'], axis=1)
final

area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [ ]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()

**Define X Features & y Target**

In [ ]:
X= final.drop('price', axis=1)
y= final.price

In [ ]:
lr.fit(X,y)

LinearRegression()

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
lr.predict([[2800,0,1]])

array([590775.63964739])

In [ ]:
lr.predict([[3400,0,0]])

array([681241.66845839])

In [ ]:
lr.score(X,y)

0.9573929037221872

#**One Hot Encoding method**

In [ ]:
df

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [ ]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

In [ ]:
dfle =df
dfle.town= le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [ ]:
# We use .values to hv 2 dimensional array & not dataframe

X = dfle[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [ ]:
y= dfle.price.values
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000])

In [ ]:

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')

In [ ]:
X = ct.fit_transform(X)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [ ]:
# To drop tyhe index and take from 1st column
X= X[:,1:]
X

array([[0.0e+00, 2.6e+03],
       [0.0e+00, 3.0e+03],
       [0.0e+00, 3.2e+03],
       [0.0e+00, 3.6e+03],
       [0.0e+00, 4.0e+03],
       [1.0e+00, 2.6e+03],
       [1.0e+00, 2.8e+03],
       [1.0e+00, 3.3e+03],
       [1.0e+00, 3.6e+03],
       [0.0e+00, 2.6e+03],
       [0.0e+00, 2.9e+03],
       [0.0e+00, 3.1e+03],
       [0.0e+00, 3.6e+03]])

In [ ]:
lr.fit(X,y)

LinearRegression()

In [ ]:
lr.predict([[0,3400]]) # 3400 sqr ft home in west windsor

array([651449.68732234])

In [ ]:
lr.predict([[0,2800]]) # 2800 sqr ft home in robbinsville

array([578535.53155202])