In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model

In [42]:
df= pd.read_csv('https://github.com/codebasics/py/raw/801ee0ee4d342fd22b89915dc0c4864250a0ec10/ML/2_linear_reg_multivariate/homeprices.csv#L4')
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [43]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [44]:
import math
median_bedrooms= math.floor(df.bedrooms.median())
median_bedrooms

4

In [45]:
# Filling Missing Values
df.bedrooms =df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [46]:
model= linear_model.LinearRegression()
model.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [47]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [48]:
model.intercept_

221323.00186540396

In [49]:
import warnings
warnings.filterwarnings("ignore")

In [50]:
model.predict([[3000,3,15]])

array([579201.19929613])

In [51]:
# Above calculation in brief
112.06244194*3000+23388.88007794*3+-3231.71790863*15 + 221323.00186540396


579201.1992897739

In [52]:
model.predict([[2000,4,5]])

array([522844.81651827])

**Exercise**


In [53]:
df= pd.read_csv('https://github.com/codebasics/py/raw/801ee0ee4d342fd22b89915dc0c4864250a0ec10/ML/2_linear_reg_multivariate/Exercise/hiring.csv#L4')
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [54]:
!pip install word2number

In [55]:
df['experience']= df['experience'].fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

**Converting Word to Number**

In [56]:
# Changing word to number
from word2number import w2n
df['experience']= df['experience'].apply(w2n.word_to_num)


In [57]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [60]:
# Handling test Score
import math
mean_score= math.floor(df['test_score(out of 10)'].mean())
mean_score

7

In [62]:
df['test_score(out of 10)']= df['test_score(out of 10)'].fillna(mean_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [64]:
model= linear_model.LinearRegression()
model.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [65]:
model.predict([[2,9,6]])

array([53713.86677124])

In [66]:
model.predict([[12,10,10]])

array([93747.79628651])