**Import Dependencies**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


In [3]:
from sklearn.datasets import load_digits
digits= load_digits()

**Train test Split**

In [4]:
X= digits.data
y= digits.target

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test =train_test_split(X,y, test_size=0.3)

In [6]:
import warnings
warnings.filterwarnings("ignore")

In [7]:
lr= LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9703703703703703

In [8]:
svm= SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.987037037037037

In [9]:
rf= RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9629629629629629

In [10]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index, test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [12]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)


In [13]:
print(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
print(get_score(SVC(), X_train, X_test, y_train, y_test))
print(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

0.9703703703703703
0.987037037037037
0.9611111111111111


In [14]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=3)

In [15]:


scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [16]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [17]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [18]:
scores_rf

[0.9415692821368948, 0.9582637729549248, 0.9415692821368948]

**Cross Validation Score**

In [19]:
from sklearn.model_selection import cross_val_score

In [22]:
print(cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3))
print(cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3))
print(cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3))

[0.89482471 0.95325543 0.90984975]
[0.38063439 0.41068447 0.51252087]
[0.93322204 0.94323873 0.91318865]


In [23]:
# This method did the same as done by the for loop

**Parameter**

In [24]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8842240844196152

In [25]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.943240223463687

In [26]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9432433271260086

In [27]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9437864680322781